#https://www.hackerrank.com/challenges/weather-observation-station-7/problem?isFullScreen=true

solution:
SELECT DISTINCT CITY
FROM STATION
WHERE CITY LIKE "%A";
SELECT DISTINCT CITY
FROM STATION
WHERE CITY LIKE "%E";
SELECT DISTINCT CITY
FROM STATION
WHERE CITY LIKE "%I";
SELECT DISTINCT CITY
FROM STATION
WHERE CITY LIKE "%O";
SELECT DISTINCT CITY
FROM STATION
WHERE CITY LIKE "%U";
